schema: "classroom50/repo-config/v1"
classroom: "ds112"
assignment: "portfolio"
owner:
  username: "adodero12"
  id: 326763085
  accepted_at: "2026-09-09T16:15:02Z"
source:
  owner: "mac-ds112-f26"
  owner_id: 323651608
  repo: "portfolio-template"
  branch: "main"
